version: '3.3'
services:
    agroturbo-api-db:
        container_name: padoca-api-db
        image: postgres:10.5-alpine
        environment:
          -  "POSTGRES_DB=padoca"
          -  "POSTGRES_USER=root"
          -  "POSTGRES_PASSWORD=root"
        ports:
          - 5432:5432